"""initial_tables

Revision ID: 07114d0d86da
Revises: 
Create Date: 2026-05-05 22:57:40.619578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07114d0d86da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('kingdom', sa.String(length=100), nullable=True),
    sa.Column('phylum', sa.String(length=100), nullable=True),
    sa.Column('class', sa.String(length=100), nullable=True),
    sa.Column('order', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('genus', sa.String(length=100), nullable=True),
    sa.Column('inaturalist_id', sa.Integer(), nullable=True),
    sa.Column('ebird_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_ebird_code'), 'species', ['ebird_code'], unique=False)
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_index(op.f('ix_species_inaturalist_id'), 'species', ['inaturalist_id'], unique=False)
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synced', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sightings_id'), 'sightings', ['id'], unique=False)
    op.create_index(op.f('ix_sightings_local_id'), 'sightings', ['local_id'], unique=False)
    op.create_index(op.f('ix_sightings_species_id'), 'sightings', ['species_id'], unique=False)
    op.create_index(op.f('ix_sightings_user_id'), 'sightings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sightings_user_id'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_species_id'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_local_id'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_id'), table_name='sightings')
    op.drop_table('sightings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_index(op.f('ix_species_inaturalist_id'), table_name='species')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_index(op.f('ix_species_ebird_code'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
